media:
  input: public/images
  output: /images

content:
  - name: blog
    label: ブログ
    type: collection
    path: content/blog
    filename:
      template: "{primary}.md"
      field: true
    delimiters: "---"
    fields:
      - name: title
        type: string
        required: true
      - name: description
        type: string
        required: true
      - name: emoji
        type: string
      - name: date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: tags
        type: string
        list: true
      - name: draft
        type: boolean
        default: false
      - name: body
        type: rich-text